CREATE TABLE CITY
(
ID NUMBER(11),
NAME VARCHAR(50)
);
CREATE TABLE REFEREE
(ID NUMBER(11),
NAME VARCHAR(50)
);
CREATE TABLE INNINGS
( ID NUMBER(11),
INNINGS_NUMBER NUMBER(11)
);

CREATE TABLE EXTRA_TYPE
( ID NUMBER(11),
NAME VARCHAR(50)
);
create table SKILL
( ID NUMBER(11),
NAME VARCHAR(50)
);

create table TEAM
( ID NUMBER(11),
NAME VARCHAR(50),
COACH VARCHAR(50),
HOME_CITY NUMBER(11),
CAPTAIN NUMBER(11)
);

create table PLAYER
( ID NUMBER(11),
NAME VARCHAR(50),
COUNTRY VARCHAR(50),
SKILL_ID NUMBER(11),
TEAM_ID NUMBER(11)
);

create table VENUE
( ID NUMBER(11),
STADIUM_NAME VARCHAR(50),
CITY_ID NUMBER(11)
);
create table EVENT
( ID NUMBER(11),
INNINGS_ID NUMBER(11),
EVENT_NO NUMBER(11),
RAIDER_ID NUMBER(11),
RAID_POINTS NUMBER(11),
DEFENDING_POINTS NUMBER(11),
CLOCK_IN_SECONDS NUMBER(11),
TEAM_ONE_SCORE NUMBER(11),
TEAM_TWO_SCORE NUMBER(11)
);

create table EXTRA_EVENT
( ID NUMBER(11),
EVENT_ID NUMBER(11),
EVENT_TYPE_ID NUMBER(11),
POINTS NUMBER(11),
SCORING_TEAM_ID NUMBER(11)
);
create table OUTCOME
(ID NUMBER(11),
STATUS VARCHAR(100),
WINNER_TEAM_ID NUMBER(11),
SCORE NUMBER(11),
PLAYER_OF_MATCH NUMBER(11)
);

create table GAME
( ID NUMBER(11),
GAME_DATE DATE,
TEAM_ID_1 NUMBER(11),
TEAM_ID_2 NUMBER(11),
VENUE_ID NUMBER(11),
OUTCOME_ID NUMBER(11),
REFEREE_ID_1 NUMBER(11),
REFEREE_ID_2 NUMBER(11),
FIRST_INNINGS_ID NUMBER(11),
SECOND_INNINGS_ID NUMBER(11)
);

DROP TABLE CITY;
DROP TABLE INNINGS;
DROP TABLE SKILL;
DROP TABLE EXTRA_TYPE;